services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8880:8000'
    restart: "no"
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'  # Porta db

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'  # vai su http://localhost:8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
